apiVersion: v1
kind: Pod
metadata:
 name: emptydir-demo
spec:
 containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "while true; do date >> /shared/date.txt; sleep 5; done"]
    
    volumeMounts:
     - name: shared-storage
       mountPath: /shared

  - name: reader
    image: busybox
    command: ["sh", "-c", "while true; do cat /shared/date.txt; sleep 5; done"]

    volumeMounts:
     - name: shared-storage
       mountPath: /shared
 volumes:
  - name: shared-storage
    emptyDir: {}
