apiVersion: v1
kind: Pod

metadata:
  name: pvc-demo

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: storage
      mountPath: /usr/share/nginx/html

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: demo-pvc
